//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcGestaoLivros.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public string nome_funcionario { get; set; }
        public string cc_funcionario { get; set; }
        public Nullable<System.DateTime> data_nascimento_funcionario { get; set; }
        public string email_funcionario { get; set; }
        public string contato_funcionario { get; set; }
        public int id_funcionario { get; set; }
        public int id_login { get; set; }
    
        public virtual login login { get; set; }
    }
}
