//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcGestaoLivros.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public login()
        {
            this.Funcionarios = new HashSet<Funcionario>();
            this.Utentes = new HashSet<Utente>();
        }

        [DisplayName("ID")]
        public int id_login { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "O Campo é obrigatório")]
        public string email { get; set; }
        [DisplayName("Nome de utilizador")]
        [Required(ErrorMessage = "O Campo é obrigatório")]
        public string username { get; set; }  

        [DataType(DataType.Password)]
        [DisplayName("Palavra passe")]
        [StringLength(10, ErrorMessage = "deve inserir entre 3 á 10 caracteres", MinimumLength = 3)]
        [Required(ErrorMessage = "Palavra passe é obrigatório")]
        public string password { get; set; }



       
        [Required]
        [StringLength(10, ErrorMessage = "deve inserir entre 3 á 10 caracteres", MinimumLength = 5)]
        [DisplayName("Confirmar Palavra passe")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        [NotMapped]
        public string RePassword { get; set; }
        [Required(ErrorMessage = "O Campo é obrigatório")]
        [DisplayName("Tipo de Utilizador")]

        public Nullable<bool> flagAtiva { get; set; }
        public Nullable<bool> privilegio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utente> Utentes { get; set; }
    }
}
