//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcGestaoLivros.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Utente
    {
        public int id_utente { get; set; }
        [Required(ErrorMessage = "O Campo é obrigatório")]
        public string nome_utente { get; set; }
        [Required(ErrorMessage = "O Campo é obrigatório")]

        public string endereco_utente { get; set; }
        public Nullable<System.DateTime> dta_nascim_utente { get; set; }
        public Nullable<int> num_tlm_utente { get; set; }
        [Required(ErrorMessage = "O Campo é obrigatório")]
        public Nullable<int> id_login { get; set; }
    
        public virtual login login { get; set; }
    }
}
