//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Autore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autore()
        {
            this.Livro_Autor = new HashSet<Livro_Autor>();
        }
    
        public int id_autor { get; set; }
        [Required(ErrorMessage = " nome autor - Campo deve ser preenchido")]
        public string nome_autor { get; set; }
        public string email_autor { get; set; }
        public string obs_autor { get; set; }
        public Nullable<System.DateTime> dataNascimento_autor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livro_Autor> Livro_Autor { get; set; }
    }
}
