//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbDsEntities : DbContext
    {
        public dbDsEntities()
            : base("name=dbDsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autore> Autores { get; set; }
        public virtual DbSet<Details_Emprestimo> Details_Emprestimo { get; set; }
        public virtual DbSet<Emprestimo> Emprestimos { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<Livro_Autor> Livro_Autor { get; set; }
        public virtual DbSet<Livro> Livros { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<Utente> Utentes { get; set; }
    
        public virtual int sp_CreateFuncionario(string email, string passworduser, string nome_funcionario, string cc_funcionario, Nullable<System.DateTime> data_nascimento_funcionario, Nullable<int> contato_funcionario)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passworduserParameter = passworduser != null ?
                new ObjectParameter("passworduser", passworduser) :
                new ObjectParameter("passworduser", typeof(string));
    
            var nome_funcionarioParameter = nome_funcionario != null ?
                new ObjectParameter("nome_funcionario", nome_funcionario) :
                new ObjectParameter("nome_funcionario", typeof(string));
    
            var cc_funcionarioParameter = cc_funcionario != null ?
                new ObjectParameter("cc_funcionario", cc_funcionario) :
                new ObjectParameter("cc_funcionario", typeof(string));
    
            var data_nascimento_funcionarioParameter = data_nascimento_funcionario.HasValue ?
                new ObjectParameter("data_nascimento_funcionario", data_nascimento_funcionario) :
                new ObjectParameter("data_nascimento_funcionario", typeof(System.DateTime));
    
            var contato_funcionarioParameter = contato_funcionario.HasValue ?
                new ObjectParameter("contato_funcionario", contato_funcionario) :
                new ObjectParameter("contato_funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateFuncionario", emailParameter, passworduserParameter, nome_funcionarioParameter, cc_funcionarioParameter, data_nascimento_funcionarioParameter, contato_funcionarioParameter);
        }
    
        public virtual int sp_CreateUtente(string email, string passworduser, string nome_utente, string endereco_utente, Nullable<System.DateTime> dta_nascim_utente, Nullable<int> num_tlm_utente)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passworduserParameter = passworduser != null ?
                new ObjectParameter("passworduser", passworduser) :
                new ObjectParameter("passworduser", typeof(string));
    
            var nome_utenteParameter = nome_utente != null ?
                new ObjectParameter("nome_utente", nome_utente) :
                new ObjectParameter("nome_utente", typeof(string));
    
            var endereco_utenteParameter = endereco_utente != null ?
                new ObjectParameter("endereco_utente", endereco_utente) :
                new ObjectParameter("endereco_utente", typeof(string));
    
            var dta_nascim_utenteParameter = dta_nascim_utente.HasValue ?
                new ObjectParameter("dta_nascim_utente", dta_nascim_utente) :
                new ObjectParameter("dta_nascim_utente", typeof(System.DateTime));
    
            var num_tlm_utenteParameter = num_tlm_utente.HasValue ?
                new ObjectParameter("num_tlm_utente", num_tlm_utente) :
                new ObjectParameter("num_tlm_utente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateUtente", emailParameter, passworduserParameter, nome_utenteParameter, endereco_utenteParameter, dta_nascim_utenteParameter, num_tlm_utenteParameter);
        }
    
        public virtual ObjectResult<sp_criarLivroAutor_Result> sp_criarLivroAutor(Nullable<int> idbook, string titulo_livro, string editorProdutora_livro, string genero_livro, Nullable<int> qtd_livro, string obs_livro, Nullable<long> isbn_livro, Nullable<int> numpaginas_livro, byte[] piccapa_livro, string nome_autor, string email_autor, string obs_autor, Nullable<System.DateTime> dataNascimento_autor, Nullable<bool> flagAtivo_livro)
        {
            var idbookParameter = idbook.HasValue ?
                new ObjectParameter("idbook", idbook) :
                new ObjectParameter("idbook", typeof(int));
    
            var titulo_livroParameter = titulo_livro != null ?
                new ObjectParameter("titulo_livro", titulo_livro) :
                new ObjectParameter("titulo_livro", typeof(string));
    
            var editorProdutora_livroParameter = editorProdutora_livro != null ?
                new ObjectParameter("editorProdutora_livro", editorProdutora_livro) :
                new ObjectParameter("editorProdutora_livro", typeof(string));
    
            var genero_livroParameter = genero_livro != null ?
                new ObjectParameter("genero_livro", genero_livro) :
                new ObjectParameter("genero_livro", typeof(string));
    
            var qtd_livroParameter = qtd_livro.HasValue ?
                new ObjectParameter("qtd_livro", qtd_livro) :
                new ObjectParameter("qtd_livro", typeof(int));
    
            var obs_livroParameter = obs_livro != null ?
                new ObjectParameter("obs_livro", obs_livro) :
                new ObjectParameter("obs_livro", typeof(string));
    
            var isbn_livroParameter = isbn_livro.HasValue ?
                new ObjectParameter("isbn_livro", isbn_livro) :
                new ObjectParameter("isbn_livro", typeof(long));
    
            var numpaginas_livroParameter = numpaginas_livro.HasValue ?
                new ObjectParameter("numpaginas_livro", numpaginas_livro) :
                new ObjectParameter("numpaginas_livro", typeof(int));
    
            var piccapa_livroParameter = piccapa_livro != null ?
                new ObjectParameter("piccapa_livro", piccapa_livro) :
                new ObjectParameter("piccapa_livro", typeof(byte[]));
    
            var nome_autorParameter = nome_autor != null ?
                new ObjectParameter("nome_autor", nome_autor) :
                new ObjectParameter("nome_autor", typeof(string));
    
            var email_autorParameter = email_autor != null ?
                new ObjectParameter("email_autor", email_autor) :
                new ObjectParameter("email_autor", typeof(string));
    
            var obs_autorParameter = obs_autor != null ?
                new ObjectParameter("obs_autor", obs_autor) :
                new ObjectParameter("obs_autor", typeof(string));
    
            var dataNascimento_autorParameter = dataNascimento_autor.HasValue ?
                new ObjectParameter("dataNascimento_autor", dataNascimento_autor) :
                new ObjectParameter("dataNascimento_autor", typeof(System.DateTime));
    
            var flagAtivo_livroParameter = flagAtivo_livro.HasValue ?
                new ObjectParameter("flagAtivo_livro", flagAtivo_livro) :
                new ObjectParameter("flagAtivo_livro", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_criarLivroAutor_Result>("sp_criarLivroAutor", idbookParameter, titulo_livroParameter, editorProdutora_livroParameter, genero_livroParameter, qtd_livroParameter, obs_livroParameter, isbn_livroParameter, numpaginas_livroParameter, piccapa_livroParameter, nome_autorParameter, email_autorParameter, obs_autorParameter, dataNascimento_autorParameter, flagAtivo_livroParameter);
        }
    
        public virtual ObjectResult<sp_getAllEmprestimos_Result> sp_getAllEmprestimos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllEmprestimos_Result>("sp_getAllEmprestimos");
        }
    
        public virtual ObjectResult<sp_GetEmprestimo_Result> sp_GetEmprestimo(Nullable<int> emprestimoID)
        {
            var emprestimoIDParameter = emprestimoID.HasValue ?
                new ObjectParameter("emprestimoID", emprestimoID) :
                new ObjectParameter("emprestimoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEmprestimo_Result>("sp_GetEmprestimo", emprestimoIDParameter);
        }
    
        public virtual ObjectResult<sp_GetEmprestimoUtente_Result> sp_GetEmprestimoUtente(Nullable<int> utenteID, Nullable<int> emprestimoID)
        {
            var utenteIDParameter = utenteID.HasValue ?
                new ObjectParameter("utenteID", utenteID) :
                new ObjectParameter("utenteID", typeof(int));
    
            var emprestimoIDParameter = emprestimoID.HasValue ?
                new ObjectParameter("emprestimoID", emprestimoID) :
                new ObjectParameter("emprestimoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEmprestimoUtente_Result>("sp_GetEmprestimoUtente", utenteIDParameter, emprestimoIDParameter);
        }
    
        public virtual ObjectResult<sp_getLivro_Result> sp_getLivro(Nullable<int> livroID)
        {
            var livroIDParameter = livroID.HasValue ?
                new ObjectParameter("livroID", livroID) :
                new ObjectParameter("livroID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLivro_Result>("sp_getLivro", livroIDParameter);
        }
    
        public virtual int sp_GetUsers(Nullable<int> idUser, Nullable<bool> flag)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetUsers", idUserParameter, flagParameter);
        }
    
        public virtual ObjectResult<sp_ListaLivroAutores_Result> sp_ListaLivroAutores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaLivroAutores_Result>("sp_ListaLivroAutores");
        }
    
        public virtual ObjectResult<sp_procurarLivro_Result> sp_procurarLivro(string tituloLivro)
        {
            var tituloLivroParameter = tituloLivro != null ?
                new ObjectParameter("tituloLivro", tituloLivro) :
                new ObjectParameter("tituloLivro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_procurarLivro_Result>("sp_procurarLivro", tituloLivroParameter);
        }
    }
}
