//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Details_Emprestimo
    {
        public int id_Details_Empres { get; set; }
        [Required(ErrorMessage = "ID emprestimo -  Campo obrigatório")]

        public Nullable<int> id_emprestimo { get; set; }
        [Required(ErrorMessage = "ID LIVRO - Campo obrigatório")]
        public Nullable<int> id_livro { get; set; }
    
        public virtual Emprestimo Emprestimo { get; set; }
        public virtual Livro Livro { get; set; }
    }
}
