//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Emprestimo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprestimo()
        {
            this.Details_Emprestimo = new HashSet<Details_Emprestimo>();
        }
    
        public int id_emprestimo { get; set; }
        [Required(ErrorMessage = "ID utente - Campo deve ser preenchido")]
        public int id_utente { get; set; }
        [Required(ErrorMessage = "data requisicao emprestimo - Campo deve ser preenchido")]
        public Nullable<System.DateTime> data_requisicao_emprestimo { get; set; }

        public Nullable<System.DateTime> data_devolucao_emprestimo { get; set; }

        public Nullable<System.DateTime> data_entrega_emprestimo { get; set; }
        public string obs_emprestimo { get; set; }
        [Required(ErrorMessage = "Status emprestimo - Campo deve ser preenchido")]

        public string status_emprestimo { get; set; }
        public string multa_valor_emprestimo { get; set; }
        public Nullable<bool> flagAtiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Emprestimo> Details_Emprestimo { get; set; }
        public virtual Utente Utente { get; set; }
    }
}
