//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Livro_Autor
    {
        public int livroAutorID { get; set; }
        [Required(ErrorMessage = "ID Livro - Campo deve ser preenchido")]
        public int id_livro { get; set; }
        [Required(ErrorMessage = "ID autor - Campo deve ser preenchido")]
        public int id_autor { get; set; }
    
        public virtual Autore Autore { get; set; }
        public virtual Livro Livro { get; set; }
    }
}
