//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livro()
        {
            this.Details_Emprestimo = new HashSet<Details_Emprestimo>();
            this.Livro_Autor = new HashSet<Livro_Autor>();
        }
    
        public int id_livro { get; set; }
        [Required(ErrorMessage = "Titulo - Campo deve ser preenchido")]
        public string titulo_livro { get; set; }
        [Required(ErrorMessage = "Editpr/Produtor - Campo deve ser preenchido")]
        public string editorProdutora_livro { get; set; }
        [Required(ErrorMessage = "Deve ser preenchido - Campo deve ser preenchido")]
        public string genero_livro { get; set; }
        public Nullable<bool> flagAtivo { get; set; }
        [Required(ErrorMessage = "Quantidade em stoque - Campo deve ser preenchido")]
        public Nullable<int> qtd_livro { get; set; }
        public string obs_livro { get; set; }
        public long isbn_livro { get; set; }
        public Nullable<int> numpaginas_livro { get; set; }
        public byte[] piccapa_livro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Emprestimo> Details_Emprestimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livro_Autor> Livro_Autor { get; set; }
    }
}
