//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Utente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utente()
        {
            this.Emprestimos = new HashSet<Emprestimo>();
        }
    
        public int id_utente { get; set; }
        [Required(ErrorMessage = "nome completo - Campo deve ser preenchido")]

        public string nome_utente { get; set; }
        [Required(ErrorMessage = "endreço utente - Campo deve ser preenchido")]
        public string endereco_utente { get; set; }
        public Nullable<System.DateTime> dta_nascim_utente { get; set; }
        public Nullable<int> num_tlm_utente { get; set; }
        [Required(ErrorMessage = "id login - Campo deve ser preenchido")]

        public Nullable<int> id_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprestimo> Emprestimos { get; set; }
        public virtual login login { get; set; }
    }
}
